### PR TITLE
refactor: incorrect handling of side effects

### PR DESCRIPTION
**Pull request by Zysd836**

### CODE REVIEW

**Comment by Zysd836** [comment]
I noticed that some components in the project were handling side effects, like event listeners, outside of React’s lifecycle methods. This can cause memory leaks and make the code harder to maintain. To help improve the project, I’ve refactored these parts.

This change not only keeps things clean and efficient but also ensures better performance and maintainability in the long run.

**Comment by Asfak00** [comment]
Can you attached some examples of that? Actually what is wrong here and you solve it. It will be better to understand and marge the PR quickly. Because, sometimes GitHub show me every code changed but actually not this, it's for different code formatter.

**Comment by Zysd836** [comment]
Handling side effects is a fundamental aspect of React, and you can explore it in more detail in this article: [Synchronizing with Effects](https://react.dev/learn/synchronizing-with-effects#how-to-write-an-effect).

To simplify, I’ll use a direct example from the project and add a log to observe the behavior change:
(src\Components\Home/Navbar.jsx)
### Before Refactoring:
image
image

You’ll notice that every time you click, the log appears multiple times. This happens because the event listener is being registered directly inside the component. Each time the component re-renders, a new event listener is added without removing the previous ones, causing repeated calls and unnecessary performance overhead.

---

### After Refactoring:
image
image

By placing the event listener inside `useEffect` and providing a **cleanup function** to remove it when the component unmounts or when dependencies change, we ensure that:

- **The event listener is registered only once** when the component mounts.
- **Resources are properly released**, preventing memory leaks and avoiding repeated calls.

---

⇒ When handling side effects like **event listeners**, **timers**, or **subscriptions**, using `useEffect` with a cleanup function is essential to maintain performance and prevent unwanted behavior in React applications.

**Comment by Asfak00** [comment]
Thank you @Zysd836

**Pull request merged**
