### PR TITLE
add: implement custom useScrollSpy hook and integrate with all Inputs…

### PR DESCRIPTION
**Pull request by danishzayan**

### CODE REVIEW

**Comment by Asfak00** [comment]
Great. Can you add the scrollSpy in all of the sidebar contents tab ?
Because now you add just in all of the inputs components but others
components do not have this. This is not perfect. We need to add it to all
of our components sidebar contents navigation tabs.

Can you do it for all components?

**Comment by danishzayan** [comment]
Ok merge this code, i will add the scrollSpy in all.

**Comment by Asfak00** [comment]
Ok, after review it will be Marged. Thank you for your contribution ❣️

**Comment by Asfak00** [comment]
please resolve the conflict. first marge from the product and then give pull request on production also resolve the conflict in `OTPInput.jsx `component

**Comment by danishzayan** [comment]
> please resolve the conflict. first marge from the product and then give pull request on production also resolve the conflict in `OTPInput.jsx `component

You should first merge my code with that person. Because he was not working with pull request, that's why conflicts have come. And I had pushed the code earlier but you merged his code

**Comment by danishzayan** [comment]
@rhm856591 before working on any issue first take pull request from production.

**Comment by danishzayan** [comment]
But I will resolve.

**Comment by Asfak00** [comment]
Brother the pull request is Marged already.

**Comment by danishzayan** [comment]
Ok bro.

**Comment by danishzayan** [comment]
@Asfak00 Code is not reflected in production till now.

**Comment by Asfak00** [comment]
Ok no problem. Please wait a day I'm working on a new component. Once it is
done I will push all codes in production. And then I think the conflict
will be resolved.

**Pull request merged**
