### PR TITLE
Refactor search functionality and Add features.

### PR DESCRIPTION
**Pull request by danishzayan**
### Overview
Added search functionality using Fuse.js for ZenUI component and block.

### Key Features
- [x] Fuzzy search with weighted matching on titles, descriptions, and tags
-  [x] Keyboard navigation (up/down/enter) support
- [x]  Smooth scrolling for keyboard navigation
- [x] Category-based filtering (components/blocks)
- [x] Highlighted search matches
- [x] Accessibility improvements
- [x] Performance optimized

### CODE REVIEW

**Comment by Asfak00** [comment]
Please push without `package-lock.json` file.

**Comment by danishzayan** [comment]
> Please push without `package-lock.json` file.

why??

**Comment by danishzayan** [comment]
> Please push without `package-lock.json` file.

bcz i have installed fuse.js packages so that file  is pushing...

**Comment by danishzayan** [comment]
i have pushed without `package-lock.json`

**Comment by Asfak00** [comment]
Ok

**Comment by danishzayan** [comment]
@Asfak00 can i should ignore this file in .gitignore???

**Comment by danishzayan** [comment]
@Asfak00 can i ignore this file in .gitignore???

**Pull request merged**
