### PR TITLE
Feat: Add new feature for Shine Skeleton Component, add keyframe in t…

### PR DESCRIPTION
**Pull request by phuoctaiismee**
…ailwind.config.js

### CODE REVIEW

**Comment by Asfak00** [comment]
Please add your feature screenshots or a demo video

**Comment by phuoctaiismee** [comment]
https://github.com/user-attachments/assets/d6ca0cb1-66bf-47e3-b751-d27259f5b407

**Comment by phuoctaiismee** [comment]
https://github.com/user-attachments/assets/3b7d7216-1bd9-4728-83a9-4efbcb436d47

**Comment by phuoctaiismee** [comment]
Uploading Video chưa đặt tên ‐ Được tạo bằng Clipchamp.mp4…

**Comment by phuoctaiismee** [comment]
https://github.com/user-attachments/assets/61684a0e-5751-4617-9744-bf91f80a299f

**Pull request merged**
